#custom cumponent requirements
resources:
  - url: /local/components/mini-media-player-bundle.js?v=1.10.1
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module
  - url: /hacsfiles/rgb-light-card/card.js
    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: module

# iterate and combine all tabs from directory
views: !include_dir_list lovelace/
