##############################################################
## List of members to identify
## September 19, 2020
## https://www.home-assistant.io/integrations/systemmonitor/
##############################################################
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: load_15m
    - type: processor_use
