esphome:
  name: backyard
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Manual ip config
  manual_ip:
    static_ip: !secret node_backyard_ip
    gateway: !secret wifi_esp_gateway
    subnet: !secret wifi_esp_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret node_backyard_failsafe_hotsport
    password: !secret node_backyard_failsafe_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret node_backyard_api_key

ota:
  id: ota_id
  password: !secret node_backyard_ota_key

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  id: backyard_cam
  name: 'Backyard Cam'
  resolution: 640x480
  max_framerate: 4 fps
  idle_framerate: 0 fps
  vertical_flip: false
  horizontal_mirror: false

# Flashlight
# not in use
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
  - platform: gpio
    pin: GPIO2
    id: gpio_2

light:
  - platform: binary
    output: gpio_2
    name: 'Backyard Light'
    restore_mode: ALWAYS_OFF

# PIR Sensor
binary_sensor:
  - platform: gpio
    id: backyard_motion_sensor
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
    name: 'Backyard Motion sensor'
    device_class: motion

# switches
switch:
  - platform: restart
    name: "Restart Backyard Node"