esphome:
  name: bedroom
  platform: ESP8266
  board: nodemcuv2
  includes:
    - 'rgbstriplight.h'
  on_boot:
    priority: 300.0
    then:
      - delay: 2s
      - switch.turn_on: window_strip_light_force_off

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Manual ip config
  manual_ip:
    static_ip: !secret node_bedroom_ip
    gateway: !secret wifi_esp_gateway
    subnet: !secret wifi_esp_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret node_bedroom_failsafe_hotspot
    password: !secret node_bedroom_failsafe_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret node_bedroom_api_key
  
ota:
  password: !secret node_bedroom_ota_key

sensor:
  - platform: dht
    pin: D1
    model: DHT11
    temperature:
      name: "Room Temperature"
    humidity:
      name: "Room Humidity"
    update_interval: 300s

  - platform: adc
    pin: A0
    name: "Bedroom Brightness"
    update_interval: 300s

# binary_sensor:
#   - platform: gpio
#     pin: D0
#     name: "Bedroom Motion sensor"
#     device_class: motion

# remote_receiver:
#   pin: D7
#   dump: nec

remote_transmitter:
  id: remote_transmitter_id
  pin:
    number: D8
  carrier_duty_percent: 50%

output:
  - platform: gpio
    pin: GPIO2
    id: gpio_2

light:
  - platform: binary
    output: gpio_2
    name: 'Bedroom motion blink'
  - platform: custom
    lambda: |-
      auto led_strip = new RGBStripLight(id(remote_transmitter_id));
      App.register_component(led_strip);
      return {led_strip};
    lights:
      - name: "Window Strip Light"
        id: window_strip_light
        default_transition_length: 0s
        restore_mode: ALWAYS_OFF

# switches
switch:
  - platform: restart
    name: "Restart Bedroom Node"
  - platform: template
    id: window_strip_light_force_off
    turn_on_action:
      - remote_transmitter.transmit_nec:
          address: 0xF7
          command: 0x40BF