esphome:
  name: nightcrawler
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Manual ip config
  manual_ip:
    static_ip: !secret node_nightcrawler_ip
    gateway: !secret wifi_esp_gateway
    subnet: !secret wifi_esp_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret node_nightcrawler_failsafe_hotspot
    password: !secret node_nightcrawler_failsafe_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret node_nightcrawler_api_key

ota:
  id: ota_id
  password: !secret node_nightcrawler_ota_key

# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  id: livingroom
  name: 'Livingroom Cam'
  resolution: 640x480
  max_framerate: 4 fps
  idle_framerate: 0 fps
  vertical_flip: false
  horizontal_mirror: false

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: 'Livingroom Mini Lamp'

binary_sensor:

  # Light sensor
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    id: ldr_livingroom
    name: 'Livingroom illumination'
    device_class: light

  # PIR Sensor A
  - platform: gpio
    pin: GPIO12
    id: pira
    device_class: motion

  # PIR SensorB
  - platform: gpio
    pin: GPIO13
    id: pirb
    device_class: motion

  # expose combined
  - platform: template
    id: pir_livingroom
    name: 'Livingroom Motion detector'
    device_class: motion
    lambda: !lambda |-
      if ((id(pira).state) and (id(pirb).state)) {
        return true;
      } else {
        return false;
      }

# switches
switch:
  - platform: restart
    name: "Restart Nightcrawler"